#!/bin/sh
pdfdeck -pagesize 1920,1080 -mono FiraMono-Regular -sans FiraSans-Regular -serif Charter\ Regular $* goinfo.xml
#pdfdeck -pagesize 1920,1080 -mono Go-Mono -sans Go-Regular -serif Charter\ Regular $* goinfo.xml
