#!/bin/sh
lcparms="-bar=f -vol -line -xlabel=0 -val=f -yaxis=f -title=f -fulldeck=f -csv -yaxis=f"
close="-csvcol=Date,Close"
volume="-color=lightgray -csvcol=Data,Volume"
echo '<deck><slide bg="black" fg="white">'
echo '<text xp="55"  yp="90" sp="4" align="e">1 Year Stock Performance</text>'
echo '<text xp="85"  yp="90" sp="2" align="end">(2017-02-03 to 2018-02-02)</text>'
echo '<text xp="45" yp="80" sp="1" align="c">Closing Price</text>'
echo '<text xp="75" yp="80" sp="1" align="c">Volume</text>'

cleft=35
cright=55
vleft=65
vright=85
top=80
bottom=70
ty=70

for i in AAPL AMZN FB GOOG MSFT
do
	echo "<text xp=\"15\"  yp=\"$ty\" sp=\"3.5\">$i</text>"
	echo "<text xp=\"20\" yp=\"$ty\" sp=\"2.5\" color=\"gray\"></text>"
	dchart -left=$cleft -right=$cright -top=$top -bottom=$bottom $lcparms $close    ~/Downloads/$i.csv
	dchart -left=$vleft -right=$vright -top=$top -bottom=$bottom $lcparms $volume   ~/Downloads/$i.csv
	
	top=`expr $top - 15`
	bottom=`expr $top - 10`
	ty=`expr $ty - 15`
done
echo '</slide></deck>'
